# Generated by Django 5.1.6 on 2025-02-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('genders', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('experience', models.CharField(choices=[('extremely_happy', 'Extremely Happy'), ('happy', 'Happy'), ('sad', 'Sad'), ('very_sad', 'Very Sad')], max_length=20)),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('Canada', 'Canada')], max_length=20)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
