# Generated by Django 5.1.6 on 2025-02-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='CustFeedback',
        ),
    ]
