# Generated by Django 5.1.6 on 2025-02-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDApp', '0002_rename_feedback_custfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custfeedback',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
