# Generated by Django 5.1.6 on 2025-02-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDApp', '0004_rename_custfeedback_cust_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust_feedback',
            name='genders',
        ),
    ]
