# Generated by Django 5.1.6 on 2025-02-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDApp', '0005_remove_cust_feedback_genders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_feedback',
            name='genders',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Male', max_length=20),
            preserve_default=False,
        ),
    ]
