# Generated by Django 5.1.6 on 2025-02-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDApp', '0006_cust_feedback_genders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cust_feedback',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='cust_feedback',
            name='country',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('Canada', 'Canada')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cust_feedback',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cust_feedback',
            name='experience',
            field=models.CharField(blank=True, choices=[('extremely_happy', 'Extremely Happy'), ('happy', 'Happy'), ('sad', 'Sad'), ('very_sad', 'Very Sad')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cust_feedback',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cust_feedback',
            name='genders',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cust_feedback',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cust_feedback',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cust_feedback',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
