# Generated by Django 5.1.6 on 2025-02-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDApp', '0007_rename_submitted_at_cust_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_feedback',
            name='user_image',
            field=models.ImageField(blank=True, default='CRUDApp/Images/Avatar.png', null=True, upload_to='user_images/'),
        ),
    ]
