# Generated by Django 5.1.6 on 2025-02-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDApp', '0008_alter_cust_feedback_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_feedback',
            name='user_image',
            field=models.ImageField(blank=True, default='Avatar.png', null=True, upload_to='user_images/'),
        ),
    ]
