# Generated by Django 5.1.3 on 2024-12-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddTask', models.CharField(max_length=400)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
