# Generated by Django 5.1.3 on 2024-12-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artic_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsImg', models.ImageField(upload_to='productNews_img')),
                ('newsTittle', models.CharField(max_length=200)),
                ('newsDate', models.DateField(auto_now=True)),
                ('newsDescription', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Product News',
            },
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
