# Generated by Django 5.1.3 on 2024-12-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artic_App', '0002_productnews_alter_products_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerImg', models.ImageField(upload_to='owners_img')),
                ('ownerName', models.CharField(max_length=200)),
                ('ownerType', models.CharField(max_length=200)),
                ('ownerDesc', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Shop Owners',
            },
        ),
    ]
