# Generated by Django 5.1.3 on 2024-12-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artic_App', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=200)),
                ('user_phone', models.PositiveIntegerField()),
                ('user_subject', models.CharField(max_length=400)),
                ('user_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'User Questios',
            },
        ),
    ]
