# Generated by Django 5.1.3 on 2024-12-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artic_App', '0007_userquestios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestios',
            name='user_phone',
            field=models.CharField(max_length=15),
        ),
    ]
