# Generated by Django 5.1.3 on 2024-12-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artic_App', '0011_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('ST', 'strawberry'), ('LM', 'lemon'), ('B', 'berry')], max_length=2, null=True),
        ),
    ]
